// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3RBFLQrdy9VDNaZ8_CS4exfGTFU5mDbg',
    appId: '1:572849529524:web:da651808a382244d446de1',
    messagingSenderId: '572849529524',
    projectId: 'scavenger-54568',
    authDomain: 'scavenger-54568.firebaseapp.com',
    storageBucket: 'scavenger-54568.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqo0kcl1iPCxb4nxfp23to9JBS4Dj2DAs',
    appId: '1:572849529524:android:30854d4e9b4e3c25446de1',
    messagingSenderId: '572849529524',
    projectId: 'scavenger-54568',
    storageBucket: 'scavenger-54568.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc-UtBTguOctYmwBW-jOat5TpcKxY2Kkc',
    appId: '1:572849529524:ios:06ef6849e435f1d5446de1',
    messagingSenderId: '572849529524',
    projectId: 'scavenger-54568',
    storageBucket: 'scavenger-54568.appspot.com',
    androidClientId: '572849529524-lnnk88pt0c1jjpue082ir6u1umnpkus1.apps.googleusercontent.com',
    iosClientId: '572849529524-4q79ch4g7ttavcf4jk5qvhijrfeqlom7.apps.googleusercontent.com',
    iosBundleId: 'com.example.scavenger2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc-UtBTguOctYmwBW-jOat5TpcKxY2Kkc',
    appId: '1:572849529524:ios:06ef6849e435f1d5446de1',
    messagingSenderId: '572849529524',
    projectId: 'scavenger-54568',
    storageBucket: 'scavenger-54568.appspot.com',
    androidClientId: '572849529524-lnnk88pt0c1jjpue082ir6u1umnpkus1.apps.googleusercontent.com',
    iosClientId: '572849529524-4q79ch4g7ttavcf4jk5qvhijrfeqlom7.apps.googleusercontent.com',
    iosBundleId: 'com.example.scavenger2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3RBFLQrdy9VDNaZ8_CS4exfGTFU5mDbg',
    appId: '1:572849529524:web:4098c503dd82b2de446de1',
    messagingSenderId: '572849529524',
    projectId: 'scavenger-54568',
    authDomain: 'scavenger-54568.firebaseapp.com',
    storageBucket: 'scavenger-54568.appspot.com',
  );

}